### ISSUE TITLE
Release and License 

### ISSUE THREAD

**Issue by benalb** [liamg/tml#2]
I would like to package tml for [void linux](https://voidlinux.org/), but they do not accept new packages if there is no Release and proper License.

**Comment by liamg** [comment]
Hi @benalb, that's awesome, thanks. I'm traveling today but I'll sort this out as soon as I'm back home, sometime tomorrow.

**Comment by liamg** [comment]
Sorted!

**Comment by benalb** [comment]
https://github.com/void-linux/void-packages/pull/11723
